package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// A tiny UCD-shaped input with every kind of line the parser must handle.
func fixture() map[string][]byte {
	return map[string][]byte{
		eastAsianWidth:  []byte("# comment\n\n0020..007E;Na # ascii\n1100..115F     ; W  # Hangul\nFF01..FF60;F # fullwidth\n00A1;A # ambiguous\n"),
		emojiData:       []byte("231A..231B    ; Emoji_Presentation   # watch\n00A9          ; Emoji                # copyright\n231C..231D    ; Emoji_Presentation # adjacent to nothing\n"),
		generalCategory: []byte("0300..036F    ; Mn # marks\n00AD          ; Cf # soft hyphen\n0020..007E    ; Zs # spaces\n0370..0373;Mn # more\n0374;Mn # touches\n3099..309A;Mn # kana marks\n"),
	}
}

func TestGenerateClassifiesRunesByTheThreeSources(t *testing.T) {
	src, err := generate(fixture())
	if err != nil {
		t.Fatal(err)
	}
	got := string(src)
	for _, want := range []string{
		"Code generated by tools/genwidth; DO NOT EDIT.",
		"Unicode version: " + unicodeVersion,
		`const unicodeVersion = "` + unicodeVersion + `"`,
		"var generatedWidthRanges = []widthRange{",
		"{0x00AD, 0x00AD, 0}", // Cf
		"{0x0300, 0x0374, 0}", // Mn ranges that touch are merged
		"{0x1100, 0x115F, 2}", // W
		"{0x231A, 0x231D, 2}", // two touching Emoji_Presentation ranges, merged
		"{0x3099, 0x309A, 0}", // W and Mn: zero wins
		"{0xFF01, 0xFF60, 2}", // F
	} {
		if !strings.Contains(got, want) {
			t.Errorf("output missing %q:\n%s", want, got)
		}
	}
	for _, unwanted := range []string{"0x0020", "0x00A1", "0x00A9", "{0x3099, 0x309A, 2}"} { // Na, A, Emoji, Zs, or the wrong precedence
		if strings.Contains(got, unwanted) {
			t.Errorf("output contains %s:\n%s", unwanted, got)
		}
	}
}

func TestClassifyGivesZeroPrecedenceAndJoinsOnlyEqualWidths(t *testing.T) {
	got := classify(
		[]span{{10, 20}, {30, 40}},
		[]span{{15, 25}, {41, 41}},
	)
	want := []wspan{{10, 14, 2}, {15, 25, 0}, {30, 40, 2}, {41, 41, 0}}
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("got %v, want %v", got, want)
		}
	}
}

// Two runs over the same input give byte-identical output.
func TestGenerateIsDeterministic(t *testing.T) {
	a, err := generate(fixture())
	if err != nil {
		t.Fatal(err)
	}
	b, err := generate(fixture())
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(a, b) {
		t.Error("two runs produced different output")
	}
}

func TestParseRejectsMalformedLines(t *testing.T) {
	for _, bad := range []string{"no semicolon here", "ZZZZ;W", "0300..02FF;Mn", "110000;W"} {
		if _, err := parse([]byte(bad), "x"); err == nil {
			t.Errorf("parse(%q) succeeded, want an error", bad)
		}
	}
}

func TestEmptyTablesAreAnError(t *testing.T) {
	files := fixture()
	files[emojiData] = []byte("# nothing\n")
	files[eastAsianWidth] = []byte("# nothing\n")
	if _, err := generate(files); err == nil {
		t.Error("generate succeeded with no wide runes")
	}
}

// A source whose SHA-256 differs from the pin fails without writing anything.
func TestRunRejectsAFileWithTheWrongHash(t *testing.T) {
	dir := t.TempDir()
	for _, s := range sources {
		p := filepath.Join(dir, filepath.FromSlash(s.path))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte("0000;W\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	out := filepath.Join(t.TempDir(), "tables.go")
	err := run(out, dir, false, false)
	if err == nil || !strings.Contains(err.Error(), "SHA-256") {
		t.Fatalf("run error = %v, want a SHA-256 mismatch", err)
	}
	if _, statErr := os.Stat(out); statErr == nil {
		t.Error("the output file was written despite the hash mismatch")
	}
}

func TestPinnedHashesAreWellFormed(t *testing.T) {
	seen := map[string]bool{}
	for _, s := range sources {
		if len(s.sha256) != 64 || strings.Trim(s.sha256, "0123456789abcdef") != "" {
			t.Errorf("%s: pin %q is not a lower-case SHA-256", s.path, s.sha256)
		}
		if seen[s.path] {
			t.Errorf("%s is listed twice", s.path)
		}
		seen[s.path] = true
	}
}
