package archtest

import (
	"fmt"
	"os"
	"regexp"
	"slices"
	"strings"
	"testing"
)

// .golangci.yml mirrors this package's import rules as depguard rules, so an
// editor running golangci-lint v2 flags a bad import as it is typed. The file is
// generated from the same tables (tiers, internalTiers, composition,
// statelessKits, testSupport), so it cannot drift: TestGolangciMirror fails when
// the file differs from what the tables produce. Regenerate it with
//
//	ARCHTEST_UPDATE=1 go test ./internal/archtest -run TestGolangciMirror

const golangciFile = "../../.golangci.yml"

// importAllowed reports whether the package from may import the package to, by
// every import rule of this package.
func importAllowed(from, to string) bool {
	edge := map[string]map[string]bool{from: {to: true}}
	switch {
	case len(directionViolations(edge)) > 0, len(kitViolations(edge)) > 0:
		return false
	case to == "term" && from != "term" && from != "internal/termio":
		return false // only internal/termio touches the terminal
	case slices.Contains(testSupport, mod+"/"+to):
		return false // test helpers stay out of production code
	}
	return true
}

// globOf returns the depguard files glob for the package at dir.
func globOf(dir string) string { return "**/" + dir + "/*.go" }

// nextRule matches the start of the next depguard rule (eight spaces and a name).
var nextRule = regexp.MustCompile(`\n {8}\S`)

func quote(s string) string { return fmt.Sprintf("%q", s) }

// renderGolangci returns the .golangci.yml the rules produce for pkgs, the
// module-relative directories of every package ("" is the root).
func renderGolangci(pkgs []string) string {
	slices.Sort(pkgs)
	var checked []string // packages the rules apply to
	for _, p := range pkgs {
		if !skipped(p) {
			checked = append(checked, p)
		}
	}
	allowOf := func(p string) []string {
		var out []string
		for _, q := range checked {
			if q != p && importAllowed(p, q) {
				out = append(out, q)
			}
		}
		return out
	}
	// Group packages with the same allow set into one rule.
	type group struct {
		files []string
		allow []string
	}
	var groups []*group
	byKey := map[string]*group{}
	for _, p := range checked {
		if p == "" {
			continue
		}
		allow := allowOf(p)
		key := strings.Join(allow, "|")
		g := byKey[key]
		if g == nil {
			g = &group{allow: allow}
			byKey[key] = g
			groups = append(groups, g)
		}
		g.files = append(g.files, globOf(p))
	}
	var b strings.Builder
	b.WriteString(`# GENERATED by internal/archtest (TestGolangciMirror); do not edit by hand.
# Regenerate: ARCHTEST_UPDATE=1 go test ./internal/archtest -run TestGolangciMirror
#
# golangci-lint v2 mirror of the import rules in internal/archtest, which is the
# authoritative check (it runs in go test ./...). Every rule is a strict
# allowlist: a package may import the standard library and the module packages
# listed for it, nothing else. Checked with golangci-lint v2.1.6, which CI runs.
# See docs/architecture/ARCHITECTURE_REVIEW.md section 7.
version: "2"
linters:
  default: none
  enable:
    - depguard
  settings:
    depguard:
      rules:
`)
	emit := func(name string, files, allow []string) {
		fmt.Fprintf(&b, "        %s:\n          list-mode: strict\n          files:\n", name)
		for _, f := range files {
			fmt.Fprintf(&b, "            - %s\n", quote(f))
		}
		// examples/ has directories named like packages (examples/focus); the
		// rules are for the library, which archtest also skips them for.
		b.WriteString("            - \"!**/examples/**\"\n            - \"!$test\"\n          allow:\n            - \"$gostd\"\n")
		for _, q := range allow {
			imp := mod
			if q != "" {
				imp += "/" + q
			}
			fmt.Fprintf(&b, "            - %s\n", quote(imp+"$"))
		}
	}
	// The root package: every file not under a package directory.
	var rootFiles = []string{"$all"}
	top := map[string]bool{}
	for _, p := range pkgs {
		if first, _, _ := strings.Cut(p, "/"); first != "" {
			top[first] = true
		}
	}
	for _, d := range slices.Sorted(mapsKeys(top)) {
		rootFiles = append(rootFiles, "!**/"+d+"/**")
	}
	emit("root", rootFiles, allowOf(""))
	for i, g := range groups {
		emit(fmt.Sprintf("group-%02d", i+1), g.files, g.allow)
	}
	return b.String()
}

func mapsKeys(m map[string]bool) func(yield func(string) bool) {
	return func(yield func(string) bool) {
		for k := range m {
			if !yield(k) {
				return
			}
		}
	}
}

func TestGolangciMirror(t *testing.T) {
	graph := imports(t, "../..")
	var pkgs []string
	for p := range graph {
		pkgs = append(pkgs, p)
	}
	got := renderGolangci(pkgs)
	if os.Getenv("ARCHTEST_UPDATE") == "1" {
		if err := os.WriteFile(golangciFile, []byte(got), 0o644); err != nil { // #nosec G306 -- a committed config file
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(golangciFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(want) != got {
		t.Errorf(".golangci.yml is out of date with the archtest rules; regenerate with ARCHTEST_UPDATE=1 go test ./internal/archtest -run TestGolangciMirror")
	}
}

// Each rule of this package has a counterpart in the generated file: a rule
// that forbids an import shows up as the absence of that package from the
// importer's allowlist.
func TestGolangciMirrorEncodesEachRule(t *testing.T) {
	pkgs := []string{"", "ansi", "widgets", "widgets/chart", "markdown", "focus", "tuitest", "textinput", "menu", "picker",
		"internal/termio", "internal/cellcheck", "internal/testutil", "internal/render", "term", "input", "examples/x"}
	y := renderGolangci(pkgs)
	allows := func(files, imp string) bool {
		i := strings.Index(y, quote(files))
		if i < 0 {
			t.Fatalf("no rule for %s", files)
		}
		rule := y[i:]
		if loc := nextRule.FindStringIndex(rule[1:]); loc != nil {
			rule = rule[:loc[0]+1]
		}
		return strings.Contains(rule, quote(imp+"$"))
	}
	for _, c := range []struct {
		files, imp string
		want       bool
		rule       string
	}{
		{"**/ansi/*.go", mod, false, "tier 0 must not import the runtime"},
		{"**/widgets/*.go", mod, false, "stateless kits never import the runtime"},
		{"**/widgets/*.go", mod + "/focus", false, "tier 4a must not import 4b"},
		{"**/tuitest/*.go", mod, true, "tier 4b may import the runtime"},
		{"**/menu/*.go", mod + "/picker", true, "composition allowlist"},
		{"**/menu/*.go", mod + "/textinput", false, "composition allowlist (menu composes only picker)"},
		{"**/textinput/*.go", mod + "/term", false, "only internal/termio touches term"},
		{"**/internal/termio/*.go", mod + "/term", true, "internal/termio may import term"},
		{"**/textinput/*.go", mod + "/internal/testutil", false, "test helpers stay out of production code"},
		{"**/textinput/*.go", mod + "/widgets", true, "components may import kits"},
	} {
		if got := allows(c.files, c.imp); got != c.want {
			t.Errorf("%s importing %s: allowed=%v, want %v (%s)", c.files, c.imp, got, c.want, c.rule)
		}
	}
	if !strings.Contains(y, "\"!$test\"") || !strings.Contains(y, "list-mode: strict") {
		t.Error("rules must be strict allowlists that skip test files")
	}
}
